### ISSUE TITLE
can't get dependencies installed

### ISSUE THREAD

**Issue by KTibow** [MercuryWorkshop/adrift#7]
i wanted to see if i could clean up some of the styling/structure here so i cloned the repo and ran `npm install`. it gave an error about being able to find "workspace:". so i tried pnpm. after a long time it came back with an error about node-gyp. so i deleted the root package.json and tried again with npm. it got a conflict because you have `vite-plugin-svelte` still installed (it's deprecated), so i removed it. i thought everything was ready - but then it failed to resolve "bare-client-custom", "client", and "tracker-list". what gives?

**Comment by CoolElectronics** [comment]
holy shit it's the m3-svelte guy

**Comment by CoolElectronics** [comment]
try with [edaa35e](https://github.com/MercuryWorkshop/adrift/commit/edaa35e2f110fc4ea81aff4b8bfd9a9b80d6adba)

**Comment by KTibow** [comment]
if i'm supposed to use that with npm, wouldn't vite still fail to import the dependencies?
if i'm supposed to use that with pnpm, tell me

**Comment by CoolElectronics** [comment]
sorry didn't read that part, yes pnpm is required

**Comment by KTibow** [comment]
```
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@mercuryworkshop/bare-client-custom@workspace:*" is in the dependencies but no package named "@mercuryworkshop/bare-client-custom" is present in the workspace

This error happened while installing a direct dependency of /home/kendell/Documents/Patches/adrift/frontend

Packages found in the workspace: @mercuryworkshop/adrift, client, frontend, protocol, adrift-server, adrift-tracker, tracker-list
```

**Comment by CoolElectronics** [comment]
did you clone recursively or init submodules?

**Comment by KTibow** [comment]
```
Cloning into '/home/kendell/Documents/Patches/adrift/vite-plugin-singlefile'...
remote: Repository not found.
fatal: repository 'https://github.com/CoolElectronics/vite-plugin-singlefile/' not found
fatal: clone of 'https://github.com/CoolElectronics/vite-plugin-singlefile' into submodule path '/home/kendell/Documents/Patches/adrift/vite-plugin-singlefile' failed
```

**Comment by CoolElectronics** [comment]
issues are resolved on my end, try with [ae07add](https://github.com/MercuryWorkshop/adrift/commit/ae07add617dfc6fc28934380b880610c3d1836df)

**Comment by KTibow** [comment]
```
Scope: all 11 workspace projects
..                                       |  WARN  deprecated node-pre-gyp@0.17.0
 WARN  deprecated vite-plugin-svelte@3.0.1: use @sveltejs/vite-plugin-svelte for vite2.0+ support
Downloading registry.npmjs.org/typescript/5.2.2: 7.23 MB/7.23 MB, done
Downloading registry.npmjs.org/firebase/10.3.1: 6.06 MB/6.06 MB, done
Downloading registry.npmjs.org/typescript/4.9.5: 11.62 MB/11.62 MB, done
Downloading registry.npmjs.org/@firebase/firestore/4.1.3: 6.52 MB/6.52 MB, done
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
..                                       |    +1204 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.3.83: 15.36 MB/15.36 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.3.83: 18.20 MB/18.20 MB, done
..                                       | Progress: resolved 1269, reused 2, downloaded 1196, added 1204, done
../node_modules/.pnpm/esbuild@0.11.23/node_modules/esbuild: Running postinstall script, done in 130ms
../node_modules/.pnpm/protobufjs@7.2.5/node_modules/protobufjs: Running postinstall script, done in 84ms
../node_modules/.pnpm/protobufjs@7.2.4/node_modules/protobufjs: Running postinstall script...
../node_modules/.pnpm/protobufjs@7.2.4/node_modules/protobufjs: Running postinstall script, done in 145mscript@5.2.2/nod
../node_modules/.pnpm/svelte-preprocess@5.0.4_postcss-load-config@4.0.1_postcss@8.4.29_svelte@4.2.0_typescript@5.2.2/node_modules/svelte-preprocess: Running postinstall script, done in 48ms
../node_modules/.pnpm/@swc+core@1.3.83_@swc+helpers@0.4.36/node_modules/@swc/core: Running postinstall script, done in 2../node_modules/.pnpm/esbuild@0.19.2/node_modules/esbuild: Running postinstall script, done in 144ms
../node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild: Running postinstall script, done in 233ms
../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, done in 142ms
../node_modules/.pnpm/wrtc@0.4.7/node_modules/wrtc: Running install script, failed in 116ms
.../.pnpm/wrtc@0.4.7/node_modules/wrtc install$ node scripts/download-prebuilt.js
│ /bin/sh: line 1: node-pre-gyp: command not found
└─ Failed in 116ms at /home/kendell/Documents/Patches/adrift/node_modules/.pnpm/wrtc@0.4.7/node_modules/wrtc
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by CoolElectronics** [comment]
from googling it looks like this is a general pnpm/node issue unrelated to the project specifically
try updating your node version and/or `npm install -g node-gyp node-pre-gyp`

**Comment by KTibow** [comment]
Running `n latest` did not fix it
Then this happened
```
➜  frontend git:(master) ✗ pnpm install -g node-pre-gyp
 WARN  deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
Packages: +67
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 67, reused 67, downloaded 0, added 67, done

/home/kendell/.local/share/pnpm/global/5:
+ node-pre-gyp 0.17.0 deprecated

Done in 1.3s
➜  frontend git:(master) ✗ pnpm install
Scope: all 11 workspace projects
..                                       |  WARN  deprecated node-pre-gyp@0.17.0
..                                       |    +1197 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..                                       | Progress: resolved 1262, reused 1189, downloaded 2, added 2, done
../node_modules/.pnpm/wrtc@0.4.7/node_modules/wrtc: Running install script, done in 3.9s
 WARN  Issues with peer dependencies found
.
└─┬ esbuild-plugin-d.ts 1.1.0
  └─┬ tsup 5.12.9
    └── ✕ unmet peer typescript@^4.1.0: found 5.2.2

corium
└─┬ @swc/core 1.3.83
  └── ✕ unmet peer @swc/helpers@^0.5.0: found 0.4.36

Done in 47.9s
➜  frontend git:(master) ✗ npm run dev

> frontend@1.0.0 dev
> vite

failed to load config from /home/kendell/Documents/Patches/adrift/frontend/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'micromatch' imported from /home/kendell/Documents/Patches/adrift/frontend/vite.config.js.timestamp-1694221383922-ce76a0bf99c06.mjs
Did you mean to import micromatch@4.0.5/node_modules/micromatch/index.js?
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:780:9)
    at moduleResolve (node:internal/modules/esm/resolve:829:20)
    at defaultResolve (node:internal/modules/esm/resolve:1034:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:375:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:344:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
```
(Also what would happen if you didn't use corium?)

**Comment by CoolElectronics** [comment]
not sure why micromatch is333 causing an error, it's never explicitly imported anywhere in the project
try with latest and if it still says that explicitly install micromatch

**Comment by KTibow** [comment]
Had to explicitly install it, and now I get this
```
Error:   Failed to scan for dependencies from entries:
  /home/kendell/Documents/Patches/adrift/frontend/index.html
/home/kendell/Documents/Patches/adrift/frontend/thin-wrapper.html

  ✘ [ERROR] Failed to resolve entry for package "@mercuryworkshop/bare-client-custom". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28691:11)
    at resolvePackageEntry (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28688:5)
    at tryNodeResolve (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at async resolve (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44512:26)
    at async file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44689:34
    at async requestCallbacks.on-resolve (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    ../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44679:19)
    at handlePlugins (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
    at /home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/home/kendell/Documents/Patches/adrift/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildScanner (file:///home/kendell/Documents/Patches/adrift/node_modules/.pnpm/vite@4.4.9/node_modules/vite/dist/node/chunks/dep-df561101.js:44462:26)

  The plugin "vite:dep-scan" was triggered by this import

    src/entry.ts:6:39:
      6 │ ...egisterRemoteListener } from "@mercuryworkshop/bare-client-custom";
```

**Comment by CoolElectronics** [comment]
you didn't build bare-client-custom, see https://github.com/MercuryWorkshop/adrift#before-everything

the import was going to be moved to the npm package eventually but you still need to build it manually for now

**Comment by KTibow** [comment]
Finally got the frontend running
